<?php

return [
  [
    'restaurant_id' => '1',
    'name' => 'Piatto pesce',
    'ingredients' => 'Sgombro, Cozze',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
    'price' => '12.99',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Piatto carne',
    'ingredients' => 'Maiale, Polenta',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
    'price' => '9.99',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Piatto casareccio',
    'ingredients' => 'Pancetta, Uovo, Coniglio',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
    'price' => '7.59',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Piatto africno',
    'ingredients' => 'Banane',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
    'price' => '2.04',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Piatto triste',
    'ingredients' => 'Insalata, Cipolla',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
    'price' => '4.49',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Piatto spendaccione',
    'ingredients' => 'Caviale, Tartufo, Ostriche',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
    'price' => '89.50',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Piatto americano',
    'ingredients' => 'Hamburger, Patate Fritte',
    'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing.',
    'price' => '9.99',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
];