<?php

return [
  [
    'restaurant_id' => '1',
    'name' => 'Pasta alla Carbonara',
    'ingredients' => 'Spaghetti, eggs, Pecorino Romano cheese, pancetta, black pepper.',
    'description' => 'Classic Roman pasta dish with a creamy sauce made of eggs, cheese, and pancetta.',
    'price' => '12.99',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Saltimbocca alla Romana',
    'ingredients' => 'Veal cutlets, prosciutto, sage, white wine, butter.',
    'description' => 'Veal cutlets topped with prosciutto and sage, cooked in a flavorful wine and butter sauce.',
    'price' => '16.50',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Risotto ai Funghi',
    'ingredients' => 'Arborio rice, mushrooms, Parmesan cheese, broth, herbs.',
    'description' => 'Creamy risotto cooked with assorted mushrooms and Parmesan cheese.',
    'price' => '14.75',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Bruschetta al Pomodoro',
    'ingredients' => 'Bread, tomatoes, garlic, basil, olive oil.',
    'description' => 'Grilled bread topped with diced tomatoes, garlic, basil, and drizzled with olive oil.',
    'price' => '8.50',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Cacio e Pepe',
    'ingredients' => 'Spaghetti, Pecorino Romano cheese, black pepper.',
    'description' => 'Simple yet flavorful pasta dish with cheese and black pepper.',
    'price' => '11.25',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Involtini di Melanzane',
    'ingredients' => 'Eggplant, ricotta cheese, tomato sauce, herbs.',
    'description' => 'Eggplant rolls stuffed with creamy ricotta cheese and served with tomato sauce.',
    'price' => '9.99',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'Tiramisù',
    'ingredients' => 'Ladyfingers, coffee, mascarpone cheese, cocoa powder.',
    'description' => 'Classic Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese.',
    'price' => '7.99',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'Sashimi Platter',
    'ingredients' => 'Assorted raw fish (salmon, tuna, yellowtail), wasabi, soy sauce.',
    'description' => 'Fresh slices of raw fish served with traditional condiments.',
    'price' => '24.99',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'Dragon Roll',
    'ingredients' => 'Shrimp tempura, avocado, eel, rice, eel sauce.',
    'description' => 'Inside-out sushi roll filled with tempura shrimp, avocado, and eel, topped with eel sauce.',
    'price' => '18.50',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'Rainbow Roll',
    'ingredients' => 'Crab, avocado, cucumber, assorted raw fish slices, rice.',
    'description' => 'California roll topped with an assortment of raw fish slices.',
    'price' => '22.75',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'Tempura Udon',
    'ingredients' => 'Udon noodles, tempura-fried vegetables (sweet potato, broccoli, shrimp), broth.',
    'description' => 'Japanese noodle soup with tempura-fried vegetables and shrimp.',
    'price' => '15.99',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'Spicy Tuna Roll',
    'ingredients' => 'Spicy tuna mix, cucumber, rice, sesame seeds.',
    'description' => 'Sushi roll filled with spicy tuna mix and cucumber.',
    'price' => '14.25',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'Sushi Burrito',
    'ingredients' => 'Sushi rice, raw fish (tuna, salmon), avocado, vegetables, soy sauce.',
    'description' => 'Giant sushi roll filled with a variety of ingredients, wrapped like a burrito.',
    'price' => '17.99',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'Miso Soup',
    'ingredients' => 'Miso paste, tofu, seaweed, green onions.',
    'description' => 'Traditional Japanese soup made with fermented soybean paste and other ingredients.',
    'price' => '5.50',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'Coq au Vin',
    'ingredients' => 'Chicken, red wine, mushrooms, onions, bacon.',
    'description' => 'Chicken braised in red wine with mushrooms, onions, and bacon.',
    'price' => '19.99',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'Bouillabaisse',
    'ingredients' => 'Assorted seafood (fish, shrimp, mussels), tomatoes, herbs, saffron.',
    'description' => 'Traditional Provençal fish stew with a mix of seafood and aromatic herbs.',
    'price' => '29.50',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'Duck à l\'Orange',
    'ingredients' => 'Duck breast, orange sauce, Grand Marnier.',
    'description' => 'Roast duck served with a sweet and tangy orange sauce.',
    'price' => '26.75',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'Escargots de Bourgogne',
    'ingredients' => 'Snails, garlic butter, parsley.',
    'description' => 'Burgundy-style snails cooked with garlic and butter.',
    'price' => '12.99',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'Ratatouille',
    'ingredients' => 'Tomatoes, eggplant, zucchini, bell peppers, onions.',
    'description' => 'Provencal vegetable stew made with tomatoes, eggplant, and various vegetables.',
    'price' => '16.25',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'Crème Brûlée',
    'ingredients' => 'Cream, sugar, vanilla.',
    'description' => 'Rich custard topped with caramelized sugar, a classic French dessert.',
    'price' => '9.99',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'Tarte Tatin',
    'ingredients' => 'Apples, puff pastry, caramel.',
    'description' => 'Upside-down caramelized apple tart, served with whipped cream or ice cream.',
    'price' => '14.50',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'Asado',
    'ingredients' => 'Various cuts of beef (ribs, chorizo, flank steak).',
    'description' => 'Traditional Argentine barbecue featuring different cuts of grilled meats.',
    'price' => '35.99',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'Empanadas',
    'ingredients' => 'Pastry dough, beef/chicken/cheese filling, onions, spices.',
    'description' => 'Baked pastries filled with a variety of savory ingredients.',
    'price' => '3.50',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'Matambre',
    'ingredients' => 'Flank steak, filling (vegetables, eggs, herbs).',
    'description' => 'Stuffed and rolled flank steak, grilled and thinly sliced.',
    'price' => '22.75',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'Milanesa Napolitana',
    'ingredients' => 'Breaded beef cutlet, ham, tomato sauce, mozzarella cheese.',
    'description' => 'Breaded and fried beef cutlet topped with ham, tomato sauce, and ',
    'price' => '18.50',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'Provoleta',
    'ingredients' => 'Provolone cheese, herbs.',
    'description' => 'Grilled provolone cheese often topped with herbs and spices.',
    'price' => '14.99',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'Chimichurri',
    'ingredients' => 'Parsley, garlic, vinegar, spices.',
    'description' => 'Flavorful sauce commonly served with grilled meats.',
    'price' => '5.25',
    'image' => 'le devo inserire',
    'visibility' => '0',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'Dulce de Leche',
    'ingredients' => 'Milk, sugar.',
    'description' => 'Sweet caramel spread, a popular dessert topping in Argentina.',
    'price' => '7.50',
    'image' => 'le devo inserire',
    'visibility' => '1',
  ],
];