<?php

return [
  [
    'restaurant_id' => '1',
    'name' => 'marco',
    'lastname' => 'freschi',
    'email' => 'marco@freschi.it',
    'phone' => '3445675897',
    'address' => 'via fresco di mare',
    'address_number' => '72',
    'total' => '52.30',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'marco',
    'lastname' => 'freschi',
    'email' => 'marco@freschi.it',
    'phone' => '3445675897',
    'address' => 'via fresco di mare',
    'address_number' => '72',
    'total' => '85.70',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'marco',
    'lastname' => 'freschi',
    'email' => 'marco@freschi.it',
    'phone' => '3445675897',
    'address' => 'via fresco di mare',
    'address_number' => '72',
    'total' => '23.60',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'marco',
    'lastname' => 'freschi',
    'email' => 'marco@freschi.it',
    'phone' => '3445675897',
    'address' => 'via fresco di mare',
    'address_number' => '72',
    'total' => '48.50',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'john',
    'lastname' => 'wick',
    'email' => 'john@conut.com',
    'phone' => '657432137',
    'address' => 'street j.commouel',
    'address_number' => '8a',
    'total' => '89.30',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'john',
    'lastname' => 'wick',
    'email' => 'john@conut.com',
    'phone' => '657432137',
    'address' => 'street j.commouel',
    'address_number' => '8a',
    'total' => '112.80',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'john',
    'lastname' => 'wick',
    'email' => 'john@conut.com',
    'phone' => '657432137',
    'address' => 'street j.commouel',
    'address_number' => '8a',
    'total' => '39.60',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'john',
    'lastname' => 'wick',
    'email' => 'john@conut.com',
    'phone' => '657432137',
    'address' => 'street j.commouel',
    'address_number' => '8a',
    'total' => '45.20',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'juan',
    'lastname' => 'campostela',
    'email' => 'campostela@mejico.me',
    'phone' => '567834567',
    'address' => 'calle de oro',
    'address_number' => '69',
    'total' => '22.30',
  ],
  [
    'restaurant_id' => '3',
    'name' => 'juan',
    'lastname' => 'campostela',
    'email' => 'campostela@mejico.me',
    'phone' => '567834567',
    'address' => 'calle de oro',
    'address_number' => '69',
    'total' => '65.50',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'juan',
    'lastname' => 'campostela',
    'email' => 'campostela@mejico.me',
    'phone' => '567834567',
    'address' => 'calle de oro',
    'address_number' => '69',
    'total' => '98.30',
  ],
  [
    'restaurant_id' => '4',
    'name' => 'philip',
    'lastname' => 'baguette',
    'email' => 'baguette@mrc.fr',
    'phone' => '8943256787',
    'address' => 'vie de la libertè',
    'address_number' => '45b',
    'total' => '36.30',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'philip',
    'lastname' => 'baguette',
    'email' => 'baguette@mrc.fr',
    'phone' => '8943256787',
    'address' => 'vie de la libertè',
    'address_number' => '45b',
    'total' => '68.60',
  ],
  [
    'restaurant_id' => '2',
    'name' => 'philip',
    'lastname' => 'baguette',
    'email' => 'baguette@mrc.fr',
    'phone' => '8943256787',
    'address' => 'vie de la libertè',
    'address_number' => '45b',
    'total' => '73.30',
  ],
  [
    'restaurant_id' => '1',
    'name' => 'philip',
    'lastname' => 'baguette',
    'email' => 'baguette@mrc.fr',
    'phone' => '8943256787',
    'address' => 'vie de la libertè',
    'address_number' => '45b',
    'total' => '68.20',
  ],
];